name: Update Date in README

# 触发条件
on:
  workflow_dispatch:
  # 定时触发
  schedule:
    # 每6小时获取一次
    - cron: '0 */12 * * *'

jobs:
  update-date:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Update date in README.md
        run: |
          # 获取当前日期，格式为 YYYY-MM-DD
          current_date=$(date +'%Y-%m-%d')
          
          # 使用 sed 替换 README.md 中的日期
          sed -i "s/created: .*/created: $current_date/" README.md
          sed -i "s/modified: .*/modified: $current_date/" README.md
          sed -i "s/created: .*/created: $current_date/" 自由上网，科学上网，翻墙机场推荐__自己用了好几年的机场,见过太多机场的起落，目前一直都在用的机场分享一下.md
          sed -i "s/modified: .*/modified: $current_date/" 自由上网，科学上网，翻墙机场推荐__自己用了好几年的机场,见过太多机场的起落，目前一直都在用的机场分享一下.md

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@users.noreply.github.com'
          git add README.md
          git commit -m "Update date in README.md to $current_date"
          git push
